#include"Commands/CommandData.hpp"
#include"Commands/CommandExit.hpp"
#include"Commands/CommandHello.hpp"
#include"Commands/CommandLoad.hpp"
#include"Commands/CommandWindow.hpp"
#include"Commands/CommandWindowOpenGL.hpp"
#include"Commands/CommandWindowSDLGame_1.hpp"
#include"Commands/CommandChouse.hpp"